// AI coach endpoint for the deployed Moxie Studios site. Mirrors serve.py's
// /coach contract exactly: same request {messages}, same {ok, reply, lesson}
// response, same 32-pose lesson filtering. Calls Gemini (gemini-2.5-flash)
// through Vertex AI express mode so the key stays server-side and the Google
// Cloud + Gemini hackathon gates are both satisfied. Env: GEMINI_API_KEY
// (required; a Vertex express-mode key), optional GEMINI_MODEL override.
// coach-lib.mjs here is a committed copy of mockups/coach-lib.mjs (build.sh
// guards that they stay identical). coach-prompt.mjs is generated by
// knowledge/build_coach_prompt.mjs.
import { readFileSync } from "node:fs";
import { trimHistory, sanitizeContents, filterLesson, practiceModeInstruction, cleanConcerns, compatibleLessonIds, lessonDemands, profileConcerns } from "./coach-lib.mjs";
import { SYSTEM_PROMPT } from "./coach-prompt.mjs";

const APPROVED = JSON.parse(readFileSync(new URL("./moxie-approved-curriculum.json", import.meta.url), "utf8"));
const APPROVED_IDS = Object.entries(APPROVED.lessons).map(([id, lesson]) => `${id}: ${lesson.title}; demands=${[...lessonDemands(APPROVED,id)].join(",")||"none"}`).join("\n");
const CURRICULUM_RULE = `\n\nJOYi-APPROVED CURRICULUM LOCK (highest priority): You do not author any user-facing wording, yoga lesson, pose order, hold, teaching cue, or meditation script. Return only replyKind, concerns, and an optional approved curriculumId. Extract only functional concerns from the learner's latest words: wrist_sensitive, knee_sensitive, hip_sensitive, shoulder_sensitive, lower_back_sensitive, neck_sensitive, foot_sensitive, prefer_seated, avoid_inversions, shorter_holds, current_pain, skin_injury, unknown_health, urgent_symptoms. A blister on a foot is foot_sensitive plus skin_injury. Select only a lesson whose listed demands avoid those concerns and the saved preferences. If none fits, use meditation_fallback and lesson null. Use seek_care and no lesson for urgent symptoms or a health concern you cannot safely map. In meditation mode lesson must always be null and replyKind must be meditation_library.\n${APPROVED_IDS}`;
const ACTION_RULE=`\n\nMEMBER ACTIONS: Hold natural, brief conversations and always return a short reply string plus an actions array. When asked to operate Moxie, propose only: navigate to dashboard, settings, saved_practices, saved_curriculums, library, meditation, or profile; create_challenge with practiceMode yoga or meditation and any whole-number days from 1 through 30; open_calendar; set_reminders. For take me or show me requests, use navigate. For a challenge request, default calendar true; email is true only when explicitly requested. Never claim an action already happened. The browser confirms state changes.`;
const fixedReply = (kind, lesson) => {
  if (lesson) return `I chose ${lesson.title} from JoYi's approved curriculum. The exact practice is below.`;
  if (kind === "meditation_library") return "Meditation uses Moxie's fixed guide library. Choose a quiet practice and the length that feels right.";
  if (kind === "meditation_fallback") return "I do not have a teacher-approved movement lesson that avoids pressure on that area. A fixed meditation is available instead. Do not continue movement that makes the problem worse.";
  if (kind === "seek_care") return "I cannot safely match that concern to a movement lesson. Please pause and get advice from a qualified health professional; seek urgent help for severe or rapidly worsening symptoms.";
  if (kind === "encourage") return "Take this one step at a time. Rest is always part of the practice.";
  if (kind === "off_topic") return "I can help you choose an approved Moxie yoga or meditation practice.";
  return "Tell me how much time you have and whether you want yoga, meditation, or both.";
};

const json = (o) => new Response(JSON.stringify(o), { headers: { "content-type": "application/json" } });

const COACH_SCHEMA = {
  type: "OBJECT",
  properties: {
    reply: { type: "STRING" },
    actions: { type:"ARRAY",items:{type:"OBJECT",properties:{type:{type:"STRING",enum:["navigate","create_challenge","open_calendar","set_reminders"]},destination:{type:"STRING",enum:["dashboard","settings","saved_practices","saved_curriculums","library","meditation","profile"]},practiceMode:{type:"STRING",enum:["yoga","meditation"]},days:{type:"INTEGER",minimum:1,maximum:30},calendar:{type:"BOOLEAN"},email:{type:"BOOLEAN"}},required:["type"]}},
    replyKind: { type: "STRING", enum: ["lesson_selected", "meditation_library", "meditation_fallback", "seek_care", "clarify", "encourage", "off_topic"] },
    concerns: { type: "ARRAY", items: { type: "STRING", enum: ["wrist_sensitive","knee_sensitive","hip_sensitive","shoulder_sensitive","lower_back_sensitive","neck_sensitive","foot_sensitive","prefer_seated","avoid_inversions","shorter_holds","current_pain","skin_injury","unknown_health","urgent_symptoms"] } },
    lesson: {
      type: "OBJECT", nullable: true,
      properties: {
        curriculumId: { type: "STRING", enum: Object.keys(APPROVED.lessons) },
      },
      required: ["curriculumId"],
    },
  },
  required: ["replyKind", "reply", "concerns", "actions"],
};

const cleanActions=(values,latest="",practiceMode="yoga")=>(Array.isArray(values)?values:[]).flatMap(value=>{if(!value||typeof value!=="object"||!["navigate","create_challenge","open_calendar","set_reminders"].includes(value.type))return[];const action={...value};if(action.type==="create_challenge"){const match=/\b([1-9]|[12][0-9]|30)\s*[- ]?day\b/i.exec(latest);action.days=Number(action.days||match?.[1]);action.practiceMode=["yoga","meditation"].includes(action.practiceMode)?action.practiceMode:(["yoga","meditation"].includes(practiceMode)?practiceMode:"yoga");action.calendar=action.calendar!==false;action.email=action.email===true;if(!Number.isInteger(action.days)||action.days<1||action.days>30)return[]}return[action]}).slice(0,3);

function profileText(value) {
  if (!value || typeof value !== "object" || value.enabled !== true) return "";
  const allowed = { areas: { wrists:"wrists", knees:"knees", hips:"hips", shoulders:"shoulders", lower_back:"lower back", neck:"neck" }, intentions: { stress_relief:"stress relief", mobility:"mobility", sleep:"sleep", strength:"strength", desk_reset:"a desk reset" }, equipment: { mat:"a mat", chair:"a chair", blocks:"blocks", bolster:"a bolster", wall:"a wall" }, movementOptions: { seated_options:"seated options", avoid_inversions:"avoiding inversions", shorter_holds:"shorter holds" }, rangeLevel: { just_starting:"just starting / feeling stiff", building_ease:"building ease", comfortable:"comfortable in most shapes", very_mobile:"very mobile" } };
  const many=(key,label)=>{const items=Array.isArray(value[key])?value[key]:[];const clean=[...new Set(items.filter(item=>allowed[key][item]).map(item=>allowed[key][item]))];return clean.length?`${label}: ${clean.join(", ")}`:"";};
  const parts=[many("areas","be gentle around"),many("intentions","intentions"),many("equipment","available"),many("movementOptions","preferences")];
  if(allowed.rangeLevel[value.rangeLevel])parts.push(`current range: ${allowed.rangeLevel[value.rangeLevel]}`);
  const note=typeof value.note==="string"?value.note.trim().slice(0,240):"";if(note)parts.push(`learner note: ${note}`);
  return parts.filter(Boolean).length?`\n\nPRIVATE LEARNER PRACTICE PREFERENCES (voluntary, non-medical): ${parts.filter(Boolean).join("; ")}. Use them to offer gentle options; do not diagnose, promise safety, or restate the profile unless directly useful.`:"";
}

async function gemini(messages, profile, practiceMode) {
  const model = process.env.GEMINI_MODEL || "gemini-flash-latest";
  // Backend switch, identical body + auth header, only the base URL differs.
  // "aistudio" = Gemini Developer API (AIza key); "vertex" = Vertex AI express
  // (AQ key, satisfies the Google Cloud gate). Set GEMINI_BACKEND=vertex in prod.
  const backend = process.env.GEMINI_BACKEND || "aistudio";
  const url = backend === "vertex"
    ? `https://aiplatform.googleapis.com/v1/publishers/google/models/${model}:generateContent`
    : `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`;
  const r = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json", "x-goog-api-key": process.env.GEMINI_API_KEY },
    body: JSON.stringify({
      systemInstruction: { parts: [{ text: SYSTEM_PROMPT + CURRICULUM_RULE + ACTION_RULE + profileText(profile) + practiceModeInstruction(practiceMode) }] },
      contents: sanitizeContents(messages),
      generationConfig: {
        responseMimeType: "application/json",
        responseSchema: COACH_SCHEMA,
        maxOutputTokens: 2048,
        temperature: 0.7,
      },
    }),
  });
  if (!r.ok) throw new Error(`gemini ${r.status}`);
  const data = await r.json();
  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  return JSON.parse(text);
}

export default async (req) => {
  if (!process.env.GEMINI_API_KEY) return json({ ok: false, error: "the guide is not set up yet" });
  if (req.method !== "POST") return json({ ok: false, error: "bad request" });
  let o;
  try { o = await req.json(); } catch { return json({ ok: false, error: "bad request" }); }
  const msgs = trimHistory(o.messages);
  if (!msgs.length) return json({ ok: false, error: "say something to the guide first" });
  let out;
  try { out = await gemini(msgs, o.profile, o.practiceMode); } catch { return json({ ok: false, error: "the guide is unavailable right now" }); }
  const concerns = cleanConcerns([...profileConcerns(o.profile), ...(out?.concerns || [])]);
  const allowed = new Set(compatibleLessonIds(APPROVED, concerns));
  const candidate = o.practiceMode === "meditation" || !allowed.has(out?.lesson?.curriculumId) ? null : out?.lesson;
  const lesson = filterLesson(candidate, APPROVED);
  const fallback = concerns.includes("urgent_symptoms") || concerns.includes("unknown_health") ? "seek_care" : (!lesson && concerns.length ? "meditation_fallback" : out?.replyKind);
  const actions=cleanActions(out?.actions,msgs.at(-1)?.text,o.practiceMode),challenge=actions.find(action=>action.type==="create_challenge");
  const reply=challenge?`I can prepare a ${challenge.days}-day beginner ${challenge.practiceMode} challenge. Confirm the plan below and I will add it to your Moxie calendar.`:lesson?fixedReply(fallback,lesson):String(out?.reply||fixedReply(fallback,lesson)).trim().slice(0,800);
  return json({ ok: true, reply, lesson, actions, next: !lesson && ["meditation_library","meditation_fallback"].includes(fallback) ? "meditation" : null });
};

// Answers at the site root and inside the studio folder, so the same file
// serves moxiestudio.netlify.app and the studio living under Practice
// Village without claiming a route at the root of their site.
export const config = { path: ["/coach", "/studio/coach"] };
